import csv
import os
from app import app, db, NiceClass

def import_nice_classes():
    print("🚀 Importando Classificação de Nice...")
    file_path = r"c:\Users\Acer\Documents\tecnologias\brandguardian\bpi\classificacao_nice.csv"
    
    # Se o arquivo não existir, vamos criar com o conteúdo fornecido pelo usuário
    if not os.path.exists(file_path):
        os.makedirs(os.path.dirname(file_path), exist_ok=True)
        content = """classe_numero;titulo_pt;descricao_resumida;inclui;nao_inclui;tipo
1;Produtos químicos para uso na indústria, ciência e fotografia, bem como na agricultura, horticultura e silvicultura;Produtos químicos para uso na indústria, ciência e agricultura, resinas artificiais, plásticos em bruto, adesivos industriais, adubos, etc.;- papel sensibilizado, composições para reparação de pneus, sal para conservar (não para alimentos), certos aditivos para a indústria alimentar, ingredientes para cosméticos e farmacêuticos, materiais de filtragem;- resinas naturais em bruto (Cl. 2), resinas semiprocessadas (Cl.17), preparações químicas para fins médicos/veterinários (Cl. 5), fungicidas (Cl. 5), adesivos para papelaria/doméstico (Cl. 16), sal para conservar alimentos (Cl. 30), camada de palha (Cl. 31);produto
2;Tintas, vernizes, lacas; conservantes contra a ferrugem e contra a deterioração da madeira; corantes, tintas; resinas naturais no estado bruto; metais em folhas e em pó para uso na pintura, decoração, impressão e arte;Tintas, corantes, produtos de proteção contra corrosão, vernizes, lacas, diluentes, fixadores, corantes para tingir vestuário e alimentos/bebidas;;produto
3;Preparações cosméticas e de higiene pessoal não medicinais; dentífricos não medicinais; perfumaria, óleos essenciais; preparações para branqueamento e outras substâncias para uso em lavandaria; preparações para limpar, polir, desengordurar e raspar;Produtos de toilette não medicinais e preparações de limpeza para uso doméstico;- artigos higiénicos de toilette, lenços impregnados com loções cosméticas, desodorizantes para humanos/animais, preparações para perfumar espaços, autocolantes para unhas, cera para polir, papel de lixa;- ingredientes para fabrico de cosméticos (Cl. 1), produtos desengordurantes usados em operações de fabrico (Cl. 1), produtos químicos para limpeza de chaminés (Cl. 1), desodorizantes não para humanos/animais (Cl. 5), champôs/sabões medicinais (Cl. 5), limas de unhas manuais (Cl. 8), pincéis de maquilhagem (Cl. 21), lenços/panos de limpeza (Cl. 21);produto
4;Óleos e gorduras industriais, cera; lubrificantes; produtos para absorver, regar e ligar; combustíveis e matérias iluminantes; velas, mechas para a iluminação;Óleos e gorduras industriais, combustíveis, matérias iluminantes;- óleos para preservação de alvenaria/couro, cera em bruto ou para uso industrial, energia elétrica, carburantes, biocombustíveis, aditivos não químicos para combustíveis, madeira para combustível;- óleos e gorduras industriais especiais (ex: óleos para tanaria Cl. 1, óleos para preservação de madeiras Cl. 2, óleos essenciais Cl. 3), velas de massagens cosméticas (Cl. 3) e medicinais (Cl. 5), ceras especiais (ex: cera para enxertar Cl. 1, cera para alfaiates/polir/depilar Cl. 3, cera dentária Cl. 5, lacre Cl. 16);produto
5;Preparações farmacêuticas, médicas e veterinárias; produtos higiênicos para a medicina; alimentos e substâncias dietéticas de uso medicinal ou veterinário, alimentos para bebés; suplementos alimentares para humanos e animais; emplastros, material para pensos; matérias para chumbar os dentes e para impressões dentárias; desinfetantes; produtos para a destruição de animais nocivos; fungicidas, herbicidas;Produtos farmacêuticos e outras preparações com fins médicos/veterinários;- produtos higiénicos para higiene íntima (não produtos de limpeza), fraldas para bebés/incontinência, desodorizantes não para humanos/animais, champôs/sabões/loções/dentífricos medicinais, suplementos dietéticos, substitutos de refeições/alimentos/bebidas para uso médico/veterinário;- ingredientes para fabrico de cosméticos (Cl. 1), preparações higiénicas não medicinais (Cl. 3), desodorizantes para humanos/animais (Cl. 3), ligaduras ortopédicas (Cl. 10), substitutos de refeições/alimentos/bebidas dietéticos não para uso médico/veterinário (ex: batatas fritas com baixo teor de gordura Cl. 29, barras de cereais Cl. 30, bebidas isotónicas Cl. 32);produto
6;Metais comuns e suas ligas, minerais; materiais metálicos para edificação e construção; construções metálicas transportáveis; cabos e fios metálicos não elétricos; pequenos artigos de quinquilharia metálica; contentores metálicos para armazenamento ou transporte; cofres-fortes;Metais comuns em bruto e semitrabalhado, incluindo minerais, e certos produtos feitos de metais comuns;- metais em folha ou pó para processamento (ex: para impressoras 3D), materiais de construção metálicos (ex: vias férreas, tubos), pequenos artigos de quinquilharia metálica (ex: parafusos, pregos), construções transportáveis em metal (ex: casas pré-fabricadas, piscinas), certos produtos em metais preciosos não classificados por função (ex: caixas multiusos, estátuas de metal comum);- metais e minerais usados como químicos na indústria/investigação (Cl. 1), metais em folha/pó para pintura/decoracão/arte (Cl. 2), cabos elétricos (Cl. 9) e cabos/cordas não elétricos e não metálicos (Cl. 22), tubos como partes de instalações sanitárias (Cl. 11), canos/tubos/mangueiras não metálicos (Cl. 17) e tubos rígidos não metálicos (Cl. 19), jaulas para animais domésticos (Cl. 21), certos produtos em metais preciosos classificados por função (ex: ferramentas Cl. 8, clipes para papéis Cl. 16, mobiliário Cl. 20, utensílios de cozinha Cl. 21, recipientes domésticos Cl. 21);produto
7;Máquinas, máquinas-ferramentas, ferramentas operadas por energia; motores e mecanismos (exceto motores para veículos terrestres); uniões de máquinas e componentes de transmissão (exceto transmissões para veículos terrestres); instrumentos agrícolas; chocadeiras para ovos; máquinas de venda automática;Máquinas, máquinas-ferramentas, motores;- partes de motores (arranques, silenciadores, cilindros), máquinas de polimento/limpeza (engraxadores elétricos, aspiradores), impressoras 3D, robôs industriais, veículos especiais não para transporte (varredoras, bulldozers, limpa-neves);- ferramentas manuais acionadas manualmente (Cl. 8), robôs humanóides com IA (Cl. 9), robôs cirúrgicos (Cl. 10), carros robôs (Cl. 12), motores para veículos terrestres (Cl. 12), lagartas para veículos/tratores (Cl. 12), caixas multibanco (Cl. 9), respiradores artificiais (Cl. 10), aparelhos frigoríficos (Cl. 11);produto
8;Ferramentas e utensílios manuais acionados por força manual; cutelaria; armas pessoais, exceto armas de fogo; lâminas;Ferramentas e instrumentos manuais para perfurar, modelar, cortar, furar;- ferramentas agrícolas/jardinagem manuais, ferramentas manuais para carpinteiros/artistas (martelos, cinzéis), manípulos para facas/foicinhas, acessórios para cuidados pessoais/arte corporal (lâminas, utensílios para frisar cabelo/tatuar/manicura), bombas manuais, cutelaria (facas, garfos, colheres, mesmo em metal precioso);- ferramentas acionadas por motor (Cl. 7), cutelaria cirúrgica (Cl. 10), bombas para pneus de bicicleta (Cl. 12) e para bolas (Cl. 28), armas de fogo (Cl. 13), abre-cartas (Cl. 16), manípulos para objetos classificados noutras classes (ex: punhos de bastões Cl. 18, cabos de vassouras Cl. 21), utensílios para servir/cozinha (Cl. 21), armas de esgrima (Cl. 28);produto
9;Instrumentos científicos, náuticos, geodésicos, fotográficos, cinematográficos, óticos, de pesagem, de medida, de sinalização, de controlo (inspeção), de socorro (salvamento) e de ensino; aparelhos e instrumentos para condução, distribuição, transformação, acumulação, regulação ou controlo da corrente elétrica; aparelhos para registo, transmissão, reprodução do som ou de imagens; suportes de registo magnético, discos acústicos; CDs, DVDs e outros meios de registo digital; mecanismos para aparelhos de pré-pagamento; caixas registadoras, máquinas de calcular, equipamento para processamento de dados, computadores; programas de computador; extintores;Instrumentos científicos, aparelhos elétricos/eletrónicos, programas de computador;- aparelhos de investigação científica para laboratórios, instrumentos para comando de navios, transferidores, máquinas de escritório de cartões perfurados, programas informáticos (qualquer suporte);- aparelhos eletromecânicos para cozinha (Cl. 7), dispositivos para bombear/distribuir combustíveis (Cl. 7), máquinas de barbear/tosquiadores/ferros de engomar (Cl. 8), aparelhos elétricos para aquecimento/ventilação (Cl. 11), escovas de dentes/pentes elétricos (Cl. 21), relojoaria (Cl. 14), relógios de controlo (Cl. 14), aparelhos de diversão para uso com ecrã externo (Cl. 28);produto
10;Aparelhos e instrumentos cirúrgicos, médicos, dentários e veterinários; membros, olhos e dentes artificiais; artigos ortopédicos; material de sutura; dispositivos terapêuticos e de assistência adaptados para pessoas com deficiência; dispositivos de massagem; aparelhos, dispositivos e artigos para crianças lactentes; aparelhos, dispositivos e artigos de atividade sexual;Aparelhos, instrumentos e artigos cirúrgicos, médicos, dentários, veterinários para diagnóstico, tratamento ou melhoria de função/condição;- ligaduras ortopédicas e vestuário especial médico (roupas de compressão, calçado ortopédico), artigos para menstruação/contraceção/parto (copos menstruais, preservativos, fórceps), implantes/protéses de materiais artificiais (seios artificiais, pacemakers cerebrais), mobiliário concebido para fins médicos (poltronas dentárias, mesas de operações);- curativos médicos e artigos absorventes (Cl. 5), implantes cirúrgicos de tecido vivo (Cl. 5), cigarros sem tabaco para uso médico (Cl. 5) e cigarros eletrónicos (Cl. 34), cadeiras de rodas/scooters de mobilidade (Cl. 12), mesas de massagem/camas de hospital (Cl. 20);produto
11;Aparelhos de iluminação, de aquecimento, de produção de vapor, de cozedura, de refrigeração, de secagem, de ventilação, de distribuição de água e instalações sanitárias;Aparelhos para iluminação, aquecimento, cozedura, refrigeração, ventilação, etc.;- aparelhos de ar condicionado, aquecedores de cama, botijas de água quente, almofadas/cobertores aquecidos eletricamente (não medicinais), vestuário eletricamente aquecido, chaleiras elétricas, utensílios de cozedura elétricos;- aparelhos de produção de vapor (partes de máquinas) (Cl. 7);produto
12;Veículos, aparelhos de locomoção por terra, por ar ou por água;Veículos e aparelhos de transporte de pessoas e bens;- motores para veículos terrestres, componentes de acoplamento/transmissão para veículos terrestres, veículos de sustentação por ar, veículos telecomandados (não brinquedos), partes de veículos (pára-choques, pára-brisas, pneus, lagartas);- materiais metálicos para vias férreas (Cl. 6), motores/uniões/correias não para veículos terrestres (Cl. 7), partes para motores (arranques, silenciadores) (Cl. 7), lagartas de borracha para máquinas pesadas (Cl. 7), triciclos/scooters como brinquedos (Cl. 28), máquinas varredoras automáticas (Cl. 7), auto-bombas de incêndio (Cl. 9), carrinhos de chá (Cl. 20), baterias elétricas, rádios para veículos (Cl. 9), luzes para automóveis (Cl. 11), carpetes para automóveis (Cl. 27);produto
13;Armas de fogo; munições e projéteis; explosivos; fogos de artifício;Armas de fogo e produtos pirotécnicos;;- fósforos (Cl. 34);produto
14;Metais preciosos e suas ligas; joalharia, bijutaria, pedras preciosas e semipreciosas; relojoaria e instrumentos cronométricos;Metais preciosos, joalharia, relojoaria, e partes componentes;- joalharia (incluindo imitação), botões de punho, alfinetes de gravata, porta-chaves, amuletos em joia, caixas para joias, componentes para joalharia/relojoaria (fechos, movimentos de relógio, ponteiros);- smartwatches (Cl. 9), amuletos não joias/porta-chaves (Cl. 26), objetos de arte não em metais preciosos (classificados por material), certos produtos em metais preciosos classificados por função (ex: metais em pó para pintura Cl. 2, amálgamas dentárias de ouro Cl. 5, cutelaria Cl. 8, contactos elétricos Cl. 9, pontas de caneta em ouro Cl. 16, bules de chá Cl. 21, bordados em ouro/prata Cl. 26, caixas para charutos Cl. 34);produto
15;Instrumentos musicais;Instrumentos musicais;- pianos mecânicos e acessórios, caixas de música, instrumentos de música elétricos/electrónicos;- aparelhos para registo/transmissão/amplificação/reprodução do som (Cl. 9);produto
16;Papel e cartão; produtos de impressão; artigos para encadernação; fotografias; artigos de papelaria e de escritório, exceto mobiliário; adesivos (matérias colantes) para papelaria ou para uso doméstico; materiais de desenho e materiais para artistas; pincéis; materiais de instrução e de ensino; folhas, películas e bolsas em matérias plásticas para acondicionamento e embalagem; clichés de impressão, blocos de impressão;Papel, cartão, artigos de escritório;- cutelaria para cortar papel, guilhotinas, capas/arquivos para papel, clipes, bolsas para livros de cheques, máquinas de escrever, duplicadores, artigos de pintura para artistas, pratos de aquarelas, produtos descartáveis de papel (babetes, guardanapos), sacos de papel, envelopes, obras de arte de papel/cartão;- cores (Cl. 2), ferramentas manuais para artistas (Cl. 8), aparelhos de ensino audiovisuais (Cl. 9), modelos de brincar (Cl. 28), papel fotográfico (Cl. 1), lixa (Cl. 3), cortinas de papel (Cl. 20), copos/pratos de papel (Cl. 21), roupa de cama em papel (Cl. 24), vestuário de papel (Cl. 25), papel de cigarro (Cl. 34);produto
17;Borracha, guta-percha, goma, amianto e mica em bruto ou semiprocessados e substitutos de todos estes materiais; plásticos e resinas na forma extrudida para uso na indústria; matérias para calafetar, vedar e isolar; canos, tubos e mangueiras flexíveis não metálicos;Materiais para isolamento térmico/acústico, borracha, plásticos em formas industriais;- borracha para recauchutagem de pneus, barreiras flutuantes antipoluição, fitas adesivas não para papelaria/médicas/domésticas, películas de plástico não para embalagem (ex: películas anti-encandeamento), fios elétricos de borracha/plástico não para uso têxtil, suportes de espuma para flores, matérias de enchimento em borracha/plástico, bolsas de borracha para embalagem;- mangueiras de incêndio (Cl. 9), tubagens como partes de instalações sanitárias (Cl. 11) e tubos rígidos metálicos (Cl. 6) e não metálicos (Cl. 19), vidro de isolamento para construção (Cl. 19), resinas de goma (Cl. 2), borracha para fins dentários (Cl. 5), resguardos de amianto para bombeiros (Cl. 9), remendos adesivos de borracha para reparação de tubos internos (Cl. 12), borrachas para apagar (Cl. 16);produto
18;Couro e imitações de couro; peles de animais; bagagens e malas de mão; chapéus de chuva e chapéus de sol; bengalas; chicotes, arreios e selaria; coleiras, trelas e vestuário para animais;Couro, imitações de couro e produtos feitos nestes materiais;- bagagem e bolsas de mão (malas, mochilas), etiquetas de bagagem, porta-cartões de visita e carteiras de bolso, caixas e estojos em pele/couro cartonado;- bengalas de caminhada/médicas (Cl. 10), vestuário/calçado/chapelaria em pele para humanos (Cl. 25), bolsas adaptadas a produtos (ex: para computadores Cl. 9), bolsas para câmaras (Cl. 9), malas para instrumentos musicais (Cl. 15), sacos de golfe (Cl. 28), assentadores em couro (Cl. 8), couro para polimento (Cl. 21), camurça para limpeza (Cl. 21), cintos de couro para vestuário (Cl. 25);produto
19;Materiais de construção não metálicos; tubos rígidos não metálicos para a construção; asfalto, pez e betume; construções transportáveis não metálicas; monumentos não metálicos;Materiais de construção não metálicos;- madeiras semitrabalhadas (vigas, pranchas, painéis), madeiras contraplacadas, vidro de construção (lajes, telhas), granulados de vidro para sinalização de estradas, caixas de correio em alvenaria;- produtos para conservação/impermeabilização do cimento (Cl. 1), ignífugos (Cl. 1);produto
20;Mobiliário, espelhos, molduras; contentores, não metálicos, para armazenamento ou transporte; osso, chifre, baleia ou madrepérola em bruto ou semitrabalhados; conchas; espuma-do-mar; âmbar amarelo;Móveis e partes, produtos em madeira, cortiça, cana, junco, vime, chifre, osso, marfim, baleia, concha, âmbar, madrepérola, espuma do mar, plásticos;- mobiliário metálico, mobiliário para campismo, estantes para armas, prateleiras para revistas, estores/persianas para janelas interiores, artigos de cama (colchões, almofadas), espelhos de mobiliário/casa de banho, chapas de matrícula não metálicas, pequenos artigos de quinquilharia não-metálica (parafusos, buchas), caixas de correio não em metal/alvenaria;- mobiliário para laboratórios (Cl. 9) ou uso médico (Cl. 10), estores exteriores metálicos (Cl. 6), não metálicos não têxtil (Cl. 19), e têxtil (Cl. 22), roupa de cama (Cl. 24), espelhos para produtos óticos (Cl. 9), espelhos para cirurgia/odontologia (Cl. 10), espelhos retrovisores (Cl. 12), espelhos de miras (Cl. 13), contas para bijutaria (Cl. 14), tábuas de madeira (Cl. 19), cestos para uso doméstico (Cl. 21), copos de plástico (Cl. 21), esteiras de junco (Cl. 27);produto
21;Utensílios e recipientes para uso doméstico e na cozinha; utensílios de cozinha e mesa, exceto garfos, facas e colheres; pentes e esponjas; escovas (exceto pincéis); materiais para o fabrico de escovas; material de limpeza; vidro em bruto ou semiacabado, exceto vidro de construção; loiça de vidro, porcelana e barro;Utensílios manuais para uso doméstico/cozinha, utensílios de higiene/cosmética, loiça de porcelana/cerâmica/vidro;- utensílios para uso doméstico/cozinha (mata-moscas, molas para roupa, colheres para misturar, saca-rolhas), utensílios de servir (pinças para açúcar, pás para tarte, conchas para servir), recipientes (vasos, garrafas, baldes, panelas), pequenos aparelhos manuais para picar/moer (prensas para alho, quebra-nozes), bases para pratos/garrafas, utensílios de toilete (pentes, escovas de dentes, fio dentário), artigos de jardinagem (luvas, regadores), aquários, terrários;- preparações para limpeza (Cl. 3), recipientes para armazenamento/transporte metálicos (Cl. 6) e não-metálicos (Cl. 20), pequenos aparelhos elétricos para picar/moer (Cl. 7), lâminas/aparelhos de barbear (Cl. 8), talheres de mesa (Cl. 8), ferramentas de corte manuais para cozinha (Cl. 8), pentes para piolhos (Cl. 10), raspadores de línguas (Cl. 10), utensílios de cozedura elétricos (Cl. 11), espelhos de casa de banho (Cl. 20), porcelana para próteses dentárias (Cl. 5), lentes de óculos (Cl. 9), lã de vidro para isolamento (Cl. 17), telhas em faiança (Cl. 19), vidro de construção (Cl. 19), fibras de vidro para uso têxtil (Cl. 22);produto
22;Cordas e cordéis; redes; tendas e lonas; toldos em matérias têxteis ou materiais sintéticos; velas; sacas para o transporte e armazenamento de materiais a granel; materiais para estofamento, amortecimento e enchimento, não sendo em papel, cartão, borracha ou plástico; matérias têxteis fibrosas em bruto e substitutos das mesmas;Lonas, materiais para velas, cordas, materiais de acondicionamento/enchimento, matérias fibrosas têxteis em bruto;- cordões/fios em fibra têxtil natural/artificial, papel/plástico, redes de pesca, redes para dormir, escadas em corda, coberturas de veículos não ajustadas, sacos/bolsas não classificados por função (sacos para meias, sacos para cadáveres), bolsas de embalagem em matérias têxteis, fibras de origem animal/têxteis em bruto (pelo de cabelo, casulos, juta, lã, seda);- escadas metálicas (Cl. 6), cordas para instrumentos musicais (Cl. 15) e raquetes de desporto (Cl. 28), materiais de enchimento em papel/cartão (Cl. 16), borracha/plástico (Cl. 17), redes de segurança (Cl. 9), redes de bagagem para veículos (Cl. 12), sacos de roupa para viagem (Cl. 18), redes para o cabelo (Cl. 26), sacos de golfe (Cl. 28), redes para desporto (Cl. 28), bolsas de embalagem não têxteis (classificadas por material);produto
23;Fios para uso têxtil;Fios para uso têxtil;;;;produto
24;Têxteis e substitutos de têxteis; roupa de casa; cortinas em matérias têxteis ou plástico;Tecidos e coberturas têxteis para uso doméstico;- roupa de casa (colchas, fronhas, toalhas têxteis), roupa de cama em papel, sacos-cama, forros de sacos-cama, mosquiteiros;- cobertores elétricos medicinais (Cl. 10) e não medicinais (Cl. 11), roupa de mesa em papel (Cl. 16), cortinas de segurança de amianto (Cl. 17), cortinas de bambu/contas (Cl. 20), mantas para cavalos (Cl. 18), tecidos para encadernação (Cl. 16), tecidos isolantes (Cl. 17), geotêxteis (Cl. 19);produto
25;Vestuário, calçado, chapelaria;Vestuário, calçado, chapelaria;- (consultar lista alfabética);;produto
26;Rendas e bordados, fitas e laços botões; colchetes e ilhós, alfinetes e agulhas flores artificiais; decorações para o cabelo; cabelo artificial;Artigos de costureira, cabelo natural/sintético para moda, adornos para cabelo, pequenos artigos decorativos;- perucas, cabeleiras, barbas falsas, travessões/bandoletes para cabelo, redes para cabelo, fivelas, fechos de correr, amuletos não bijutaria/porta-chaves;- pestanas falsas (Cl. 3), próteses de cabelo (Cl. 10), amuletos em joias/para porta-chaves (Cl. 14), fios para uso têxtil (Cl. 23);produto
27;Tapetes, capachos, esteiras, linóleos e outros artigos de revestimento de soalhos; tapeçarias murais não em matérias têxteis;Produtos para recobrir/revstir soalhos/paredes já construídas;;- pranchas de madeira (Cl. 19);produto
28;Jogos, brinquedos e artigos de jogar; aparelhos de videojogos; artigos de ginástica e desporto; decorações para árvores de Natal;Brinquedos, aparelhos para jogos, equipamentos desportivos, artigos de diversão/festas;- aparelhos de diversão/jogo (incluindo comandos), artigos de cotilhão (máscaras, chapéus de papel, confetti), equipamento de caça/pesca (canas de pesca, iscos), aparelhos para desportos/jogos;- velas para árvores de Natal (Cl. 4), luzes elétricas para árvores de Natal (Cl. 11), confeitaria/chocolate para árvores de Natal (Cl. 30), equipamento de mergulhadores (Cl. 9), brinquedos/bonecas sexuais (Cl. 10), vestuário de ginástica/desporto (Cl. 25), capacetes/óculos de proteção para desporto (Cl. 9), armas de fogo para desporto (Cl. 13), tapetes de ginásio (Cl. 27), facas de caça (Cl. 8), arpões (Cl. 8), armas de fogo para caça (Cl. 13), redes de pesca (Cl. 22);produto
29;Carne, peixe, aves e caça; extratos de carne; frutos e legumes em conserva, secos e cozidos; geleias, doces, compotas; ovos; leite e lacticínios; óleos e gorduras para a alimentação;Produtos alimentares de origem animal e vegetal preparados para consumo/conservação;- bebidas lácteas onde o leite é predominante, sementes preparadas para consumo humano (não temperos/aromas);- alimentos para bebés (Cl. 5), alimentos/substâncias dietéticas de uso medicinal (Cl. 5), suplementos dietéticos (Cl. 5), sementes processadas para tempero (Cl. 30), molhos para saladas (Cl. 30), ovos para incubar (Cl. 31), alimentos para animais (Cl. 31), animais vivos (Cl. 31), sementes para plantação (Cl. 31);produto
30;Café, chá, cacau e sucedâneos do café; arroz; tapioca e sagú; farinhas e preparações feitas de cereais; pão, pastelaria e confeitaria; gelados comestíveis; açúcar, mel e xarope de melaço; levedura e fermento em pó; sal; mostarda; vinagre, molhos (condimentos); especiarias; gelo (água congelada);Produtos alimentares de origem vegetal preparados e adjuvantes para melhorar gosto;- bebidas à base de café/cacau/chocolate/chá, cereais preparados para alimentação humana (flocos de aveia);- sal para conservar não para alimentos (Cl. 1), infusões medicinais (Cl. 5), alimentos/substâncias dietéticos para uso medicinal (Cl. 5), alimentos para bebés (Cl. 5), suplementos dietéticos (Cl. 5), levedura para uso farmacêutico (Cl. 5), fermento para consumo animal (Cl. 31), cereais no estado bruto (Cl. 31), alimentos para animais (Cl. 31);produto
31;Produtos de agricultura, aquacultura, horticultura e silvicultura, em bruto e não processados; grãos e sementes em bruto ou não processados; frutos e legumes frescos, ervas frescas; plantas e flores naturais; bulbos, plântulas e sementes para plantação; animais vivos; alimentos e bebidas para animais; malte;Produtos da terra/mar não processados, animais/plantas vivos, alimentos para animais;- cereais não processados, fruta/legumes frescos (mesmo lavados/encerados), resíduos vegetais, algas não processadas, madeira não cortada, ovos fertilizados para chocar, trufas/cogumelos frescos, produtos para camas/caixas de animais (areia aromática, papel de lixa para animais);- culturas de microrganismos/sanguessugas para uso medicinal (Cl. 5), suplementos dietéticos para animais/alimentação animal medicada (Cl. 5), madeiras semitrabalhadas (Cl. 19), isco artificial para pesca (Cl. 28), arroz (Cl. 30), tabaco (Cl. 34);produto
32;Cervejas; águas minerais e gasosas e outras bebidas não alcoólicas; bebidas de fruta e sumos de fruta; xaropes e outras preparações para bebidas;Bebidas não alcoólicas e cervejas;- bebidas desalcoolizadas;- bebidas para uso medicinal (Cl. 5), bebidas lácteas onde o leite predomina (Cl. 29), bebidas a base de cacau/café/chocolate (Cl. 30);produto
33;Bebidas alcoólicas (exceto cervejas);Bebidas alcoólicas (exceto cervejas);;- bebidas medicinais (Cl. 5), bebidas desalcoolizadas (Cl. 32);produto
34;Tabaco; artigos para fumadores; fósforos;Tabaco, artigos para fumadores, fósforos;- sugerâneos do tabaco (não para uso medicinal);- cigarros sem tabaco para uso medicinal (Cl. 5);produto
35;Publicidade; gestão de negócios comerciais; administração comercial; trabalhos de escritório;Serviços de ajuda na exploração/direção de empresas comerciais, serviços de publicidade;- agrupamento de produtos para terceiros (lojas, sites), registo/composição/compilação de comunicações/dados, serviços de agências de publicidade, distribuição de prospectos/amostras;- avaliações/relatórios de engenheiros não relacionados com direção de negócios;serviço
36;Seguros; negócios financeiros; negócios monetários; negócios imobiliários;Serviços financeiros, monetários, seguros, imobiliários;- serviços bancários, instituições de crédito, investment trusts, corretores de valores, agentes fiduciários, emissão de cheques de viagem, financiamento para compra a prestações/leasing, administração de imóveis (locação, avaliação), serviços de seguros (agentes, corretores);;;serviço
37;Construção; reparação; serviços de instalação;Serviços de construção, reparação, instalação;- construção de edifícios/estradas/pontes, serviços de empresas especializadas (pintores, canalizadores), inspeções de projetos, construção naval, aluguer de ferramentas/materiais de construção, reparação/restauro de objetos, conservação;;serviço
38;Telecomunicações;Serviços de telecomunicações que permitem comunicação entre pessoas;- difusão de programas de rádio/televisão;- publicidade por rádio (Cl. 35), marketing por telefone (Cl. 35);serviço
39;Transporte; embalagem e armazenagem de mercadorias; organização de viagens;Serviços de transporte de pessoas/mercadorias, armazenagem, organização de viagens;- aluguer de veículos de transporte, reboque marítimo, funcionamento de portos, embalagem/empacotamento de mercadorias, informações de viagens/transportes, inspeção de veículos/mercadorias;- publicidade de empresas de transporte (Cl. 35), emissão de cheques de viagem (Cl. 36), seguros durante transporte (Cl. 36), conservação/reparação de veículos (Cl. 37), reserva de quartos de hotel (Cl. 43);serviço
40;Tratamento de materiais;Serviços de tratamento/transformação/produção mecânica/química de objetos/substâncias;- transformação que implique modificação de propriedades essenciais (ex: tingir vestuário), tratamento durante fabrico (corte, molde, polimento), fabrico personalizado por indicação de terceiros;- serviços de reparação (Cl. 37), certos serviços de customização (ex: pintura personalizada de automóveis Cl. 37);serviço
41;Educação; formação; divertimento; atividades desportivas e culturais;Serviços para desenvolver faculdades mentais, divertimento, atividades culturais/desportivas;- educação/treino de indivíduos/animais, serviços de divertimento/entretenimento, apresentação de obras de arte/literatura;;serviço
42;Serviços científicos e tecnológicos bem como serviços de pesquisas e de conceção a eles referentes; serviços de análises e de pesquisas industriais; conceção e desenvolvimento de computadores e de programas de computadores;Serviços científicos, tecnológicos, pesquisa, conceção;- serviços de engenheiros (avaliações, pesquisas, relatórios), proteção de dados/deteção de acesso não autorizado, pesquisa científica com fins médicos;- pesquisas/avaliações em negócios comerciais (Cl.35), tratamento de texto/gestão de ficheiros (Cl. 35), avaliações financeiras/fiscais (Cl. 36), extração mineira/petróleo (Cl. 37), instalação/reparação de computadores (Cl. 37), serviços médicos/veterinários (Cl. 44), serviços de tratamentos médicos (Cl. 44), serviços de jardineiros paisagistas (Cl. 44), serviços jurídicos (Cl. 45);serviço
43;Serviços de restauração (alimentação); alojamento temporário;Serviços de preparação de alimentos/bebidas, alojamento temporário;- reserva de alojamento por viajantes, pensões para animais;- aluguer de bens imobiliários para uso permanente (Cl. 36), organização de viagens por agências (Cl. 39), conservação de alimentos/bebidas (Cl. 40), discotecas (Cl.41), pensionatos (Cl. 41), casas de repouso (Cl. 44);serviço
44;Serviços médicos; serviços veterinários; cuidados de higiene e de beleza para seres humanos e animais; serviços de agricultura, horticultura e silvicultura;Cuidados médicos, higiene corporal, beleza para humanos/animais; serviços agrícolas/hortícolas/florestais;- análises médicas (exames radiográficos, colheitas de sangue), inseminação artificial, consultas farmacêuticas, criação de animais, cultivo de plantas (jardinagem), arte floral (composição floral), serviços de jardineiros paisagistas;- destruição de pragas não para agricultura (Cl. 37), instalação/reparação de dispositivos de irrigação (Cl. 37), transporte por ambulância (Cl. 39), abate de animais/taxidermia (Cl. 40), abate árvores/venda de madeiras (Cl. 40), treino de animais (Cl. 41), clubes de cultura física (Cl. 41), pesquisa científica com fins médicos (Cl. 42), pensões para animais (Cl. 43), casas de repouso para idosos (Cl. 43);serviço
45;Serviços jurídicos; serviços de segurança para a proteção física de bens tangíveis e indivíduos; serviços pessoais e sociais prestados por terceiros destinados a satisfazer as necessidades dos indivíduos;Serviços jurídicos, segurança física, serviços pessoais/sociais;- serviços de juristas/advogados, investigação/controlo de segurança física, serviços sociais (acompanhamento em sociedade, agências matrimoniais, serviços funerários);- serviços profissionais de ajuda direta a empresas comerciais (Cl.35), serviços financeiros/seguros (Cl. 36), acompanhamento de viajantes (Cl. 39), transporte em segurança (Cl.39), educação (Cl. 41), atuações de cantores/bailarinos (Cl. 41), programação para proteção de software (Cl. 42), consultoria em segurança informática (Cl. 42), cuidados médicos/higiene/beleza (Cl. 44);serviço"""
        with open(file_path, 'w', encoding='utf-8') as f:
            f.write(content)
            
    with app.app_context():
        # Limpar tabela antes de importar para evitar duplicados ou dados antigos
        # NiceClass.__table__.drop(db.engine)
        # db.create_all()
        
        count = 0
        try:
            with open(file_path, 'r', encoding='utf-8') as f:
                reader = csv.DictReader(f, delimiter=';')
                for row in reader:
                    num = int(row.get('classe_numero'))
                    existing = NiceClass.query.filter_by(number=num).first()
                    if existing:
                        existing.title = row.get('titulo_pt')
                        existing.description = row.get('descricao_resumida')
                        existing.includes = row.get('inclui')
                        existing.excludes = row.get('nao_inclui')
                        existing.type = row.get('tipo')
                    else:
                        obj = NiceClass(
                            number=num,
                            title=row.get('titulo_pt'),
                            description=row.get('descricao_resumida'),
                            includes=row.get('inclui'),
                            excludes=row.get('nao_inclui'),
                            type=row.get('tipo')
                        )
                        db.session.add(obj)
                        count += 1
            db.session.commit()
            print(f"✅ SUCESSO! {count} Classes de Nice importadas/atualizadas.")
        except Exception as e:
            db.session.rollback()
            print(f"❌ Erro import_nice_classes: {e}")

if __name__ == '__main__':
    import_nice_classes()
